package com.explosivepomegranate.rest.api.controller;

import com.explosivepomegranate.rest.api.model.Book;
import com.explosivepomegranate.rest.api.repository.BookRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.sql.Date;

@Controller
public class BookController {

    @Autowired // This means to get the bean called bookRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BookRepository bookRepository;

    /**
     * @author: Clelia
     * get a list of all Books in the DB
     * */
    @GetMapping(path="/allBooks")
    public @ResponseBody Iterable<Book> getAllBooks() {
        return bookRepository.findAll();
    }

    /**
     * @author Clelia
     * add a new book --------still a draft, model is still incomplete and this method will require some work work
     * */
    @PostMapping(path = "/addBook")
    public @ResponseBody Book addNewBook(@RequestParam String isbn, @RequestParam String title, @RequestParam String description, @RequestParam int year) {
        Book book = new Book();
        book.setISBN(isbn);
        book.setTitle(title);
        book.setDescription(description);
        book.setYear(year);

        bookRepository.save(book);
        return book;
    }
}
